### ISSUE TITLE
Links to examples in readme are defunct

### ISSUE THREAD

**Issue by tpamula** [krasimir/kuker#14]
Hi kuker devs! I've found that the links to examples in README.md are pointing to 404 pages, e.g. https://work.krasimirtsonev.com/git/redux-react-todomvc/

**Comment by krasimir** [comment]
Hey, I'll upload the examples somewhere else the next couple of days.

**Comment by brucou** [comment]
Hi @krasimir the situation seems to be still going on. Links to examples are pointing to 404. That said the chrome extension has a very nice animation :-)

**Comment by krasimir** [comment]
I moved to another hosting provider and forgot about those examples on my website. I updated the README and created a new place https://kuker-example.now.sh/ React emitter is not working with v15 and v16. Sorry, it needs a lot more time to fix it. But Redux and redux-saga events are going through.

**Comment by brucou** [comment]
Thanks Krasimir, that's much appreciated
